import { dispatchYoutubeHotkey } from "@/lib/hotkeys/youtube-hotkey-dispatch";
import type { YoutubePlayer } from "@/lib/player";
import { YOUTUBE_HOTKEYS } from "@/lib/youtube-keymap";
import { z } from "@/lib/zod";

export enum CycleDirection {
  Forward = 1,
  Backward = -1
}

const CAPTIONS_MODULE = "captions";
const AUTO_GENERATED_KIND = "asr";
const OFF_POSITION = -1;
const NATIVE_TOGGLE_TIMEOUT_MS = 1000;

enum CaptionsOption {
  Tracklist = "tracklist",
  Track = "track"
}

const responseTrackSchema = z.looseObject({
  languageCode: z.string().min(1),
  vssId: z.string().min(1),
  kind: z.string().optional()
});

const playerResponseSchema = z.looseObject({
  captions: z.looseObject({
    playerCaptionsTracklistRenderer: z.looseObject({
      captionTracks: z.array(responseTrackSchema),
      audioTracks: z.array(z.looseObject({ defaultCaptionTrackIndex: z.number().optional() })).optional()
    })
  })
});

const activeTrackSchema = z.looseObject({ vss_id: z.string().min(1) });

const moduleTrackSchema = z.looseObject({
  languageCode: z.string(),
  vss_id: z.string()
});

type ResponseTrack = z.infer<typeof responseTrackSchema>;

function getPrimaryLanguage(languageCode: string) {
  return languageCode.split("-")[0].toLowerCase();
}

// The tracklist the captions module reports can lag behind (it showed a pre-roll ad's tracks),
// so the cycle is built from the video's own player response
function readVideoTracks(player: YoutubePlayer) {
  const parsed = playerResponseSchema.safeParse(player.getPlayerResponse?.());
  if (!parsed.success) {
    return null;
  }

  const renderer = parsed.data.captions.playerCaptionsTracklistRenderer;
  return {
    tracks: renderer.captionTracks,
    iDefault: renderer.audioTracks?.[0]?.defaultCaptionTrackIndex ?? OFF_POSITION
  };
}

// The viewer's own languages come first, then the video's default track, then YouTube's order -
// so a video with dozens of tracks reaches the useful ones in a press or two
function rankTrack({ track, iTrack, iDefault }: {
  track: ResponseTrack;
  iTrack: number;
  iDefault: number;
}) {
  const preferredLanguages = navigator.languages.map(getPrimaryLanguage);
  const iPreferred = preferredLanguages.indexOf(getPrimaryLanguage(track.languageCode));
  const isAutoGenerated = track.kind === AUTO_GENERATED_KIND;
  if (iPreferred !== -1) {
    return iPreferred * 2 + Number(isAutoGenerated);
  }

  const isDefault = iTrack === iDefault;
  return preferredLanguages.length * 2 + Number(!isDefault);
}

function orderTracks({ tracks, iDefault }: {
  tracks: ResponseTrack[];
  iDefault: number;
}) {
  const ranked = tracks.map((track, iTrack) => ({
    track,
    rank: rankTrack({
      track,
      iTrack,
      iDefault
    })
  }));
  return ranked.toSorted((first, second) => first.rank - second.rank).map(({ track }) => track);
}

function getActiveVssId(player: YoutubePlayer) {
  const parsed = activeTrackSchema.safeParse(player.getOption?.(CAPTIONS_MODULE, CaptionsOption.Track));
  return parsed.success ? parsed.data.vss_id : null;
}

function getActivePosition({ player, tracks }: {
  player: YoutubePlayer;
  tracks: ResponseTrack[];
}) {
  const activeVssId = getActiveVssId(player);
  if (activeVssId === null) {
    return OFF_POSITION;
  }

  return tracks.findIndex(track => track.vssId === activeVssId);
}

function getNextPosition({ position, direction, trackCount }: {
  position: number;
  direction: CycleDirection;
  trackCount: number;
}) {
  const stateCount = trackCount + 1;
  return (position + 1 + direction + stateCount) % stateCount - 1;
}

// setOption only accepts the captions module's own track objects; build one when its list lags
function toModuleTrack({ player, track }: {
  player: YoutubePlayer;
  track: ResponseTrack;
}) {
  const parsedTracklist = z.array(moduleTrackSchema).safeParse(
    player.getOption?.(CAPTIONS_MODULE, CaptionsOption.Tracklist, { includeAsr: true })
  );
  const moduleTrack = parsedTracklist.success ?
    parsedTracklist.data.find(candidate => candidate.vss_id === track.vssId) :
    undefined;
  return moduleTrack ?? {
    languageCode: track.languageCode,
    kind: track.kind ?? "",
    vss_id: track.vssId
  };
}

// Every on/off goes through YouTube's own caption key and every switch through its own API, so the
// feedback is YouTube's native bezel ("Subtitles/closed captions on/off") and track card - never ours
function toggleNativeCaptions(player: YoutubePlayer) {
  dispatchYoutubeHotkey({
    player,
    hotkey: YOUTUBE_HOTKEYS.captions
  });
}

// YouTube handles its caption key a beat later, so wait for it to switch captions on before
// choosing the track - setting it first would just get toggled back off
function waitForCaptionsOn(player: YoutubePlayer) {
  const startedAt = performance.now();
  return new Promise<boolean>(resolve => {
    function check() {
      if (getActiveVssId(player) !== null) {
        resolve(true);
        return;
      }

      const isTimedOut = performance.now() - startedAt > NATIVE_TOGGLE_TIMEOUT_MS;
      if (isTimedOut) {
        resolve(false);
        return;
      }

      requestAnimationFrame(check);
    }

    check();
  });
}

async function selectTrack({ player, track }: {
  player: YoutubePlayer;
  track: ResponseTrack;
}) {
  const isOff = getActiveVssId(player) === null;
  if (isOff) {
    toggleNativeCaptions(player);
    const isOn = await waitForCaptionsOn(player);
    if (!isOn) {
      return;
    }
  }

  const isAlreadyActive = getActiveVssId(player) === track.vssId;
  if (isAlreadyActive) {
    return;
  }

  player.setOption?.(
    CAPTIONS_MODULE, CaptionsOption.Track, toModuleTrack({
      player,
      track
    })
  );
}

// VLC cycles off -> each track -> off, where YouTube's own caption key only toggles
export function cycleSubtitles({ player, direction }: {
  player: YoutubePlayer;
  direction: CycleDirection;
}) {
  const videoTracks = readVideoTracks(player);
  if (!videoTracks || videoTracks.tracks.length === 0) {
    toggleNativeCaptions(player);
    return;
  }

  const tracks = orderTracks(videoTracks);
  const position = getNextPosition({
    position: getActivePosition({
      player,
      tracks
    }),
    direction,
    trackCount: tracks.length
  });
  const track = tracks[position];
  if (!track) {
    toggleNativeCaptions(player);
    return;
  }

  void selectTrack({
    player,
    track
  });
}
